import argparse
import os
import sys
from pathlib import Path
from typing import Tuple

import yaml
from PyQt6.QtWidgets import QApplication

from mill_presenter.core.cache import ResultsCache
from mill_presenter.core.playback import FrameLoader
from mill_presenter.ui.main_window import MainWindow


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="MillPresenter UI Player")
    parser.add_argument("--video", required=True, help="Path to the video file to play")
    parser.add_argument(
        "--detections",
        required=True,
        help="Path to detections JSONL generated by the detection pipeline",
    )
    parser.add_argument(
        "--config",
        default=str(Path("configs") / "sample.config.yaml"),
        help="Path to YAML config file with overlay/colors/etc.",
    )
    return parser.parse_args()


def load_config(path: str) -> dict:
    path_obj = Path(path)
    if not path_obj.exists():
        return {}
    with path_obj.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    return data


def create_main_window(config: dict, video_path: str, detections_path: str) -> Tuple[MainWindow, FrameLoader, ResultsCache]:
    frame_loader = FrameLoader(video_path)
    results_cache = ResultsCache(detections_path)
    window = MainWindow(config, frame_loader=frame_loader, results_cache=results_cache)
    return window, frame_loader, results_cache


def main():
    args = parse_args()

    config = load_config(args.config)

    app = QApplication(sys.argv)
    window, frame_loader, _ = create_main_window(config, args.video, args.detections)

    # Ensure resources are released on exit
    app.aboutToQuit.connect(frame_loader.close)

    window.show()
    sys.exit(app.exec())


if __name__ == "__main__":
    main()
